# config/packages/security.yaml

security:
  providers:
    app_user_provider:
      id: App\Security\UserProvider
  # ...
  password_hashers:
    # Use native password hasher, which auto-selects and migrates the best
    # possible hashing algorithm (which currently is "bcrypt")
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  firewalls:
    main:
      custom_authenticators:
        - App\Security\ApiKeyAuthenticator
      logout:
        path: app_logout
#      custom_authenticator: App\Security\AppCustomAuthenticator
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800
        path: /
        # by default, the feature is enabled by checking a checkbox in the
        # login form, uncomment the following line to always enable it.
        #always_remember_me: true
        #REDIRECT TO: target:
#TOKENHANDLER
#     access_token:
#        token_handler: App\Security\AccessTokenHandler